<?php
/*
 * This file is part of the PostCarrier
 *
 * Copyright(c) 2016 IPLOGIC CO.,LTD. All Rights Reserved.
 * http://www.iplogic.co.jp
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\PostCarrier\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Id\SequenceGenerator;
use Eccube\Common\Constant;

/**
 * MailmagaCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCarrierGroupCustomerRepository extends EntityRepository
{

    /*
    public function findAll() {
        $query = $this
            ->getEntityManager()
            ->createQuery('SELECT g FROM Plugin\PostCarrier\Entity\PostCarrierGroupCustomer g ORDER BY g.id DESC');
        $result = $query
            ->getResult(Query::HYDRATE_ARRAY);

        return $result;
    }
    */

    /**
     * メルマガカスタマー情報を保存する
     * @param \Plugin\PostCarrier\Entity\MailmagaCustomer $MailmagaCustomer
     */
    public function save(\Plugin\PostCarrier\Entity\PostCarrierGroupCustomer $PostCarrierGroupCustomer)
    {
        $em = $this->getEntityManager();
        $em->persist($PostCarrierGroupCustomer);
        $em->flush();
    }

    public function delete(\Plugin\PostCarrier\Entity\PostCarrierGroupCustomer $PostCarrierGroupCustomer)
    {
        $em = $this->getEntityManager();
        $em->remove($PostCarrierGroupCustomer);
        $em->flush();
    }
}
