<?php
/*
 * This file is part of the PostCarrier
 *
 * Copyright(c) 2016 IPLOGIC CO.,LTD. All Rights Reserved.
 * http://www.iplogic.co.jp
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\PostCarrier\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCarrierPluginRepository extends EntityRepository
{
    public function getSubData($pluginCode)
    {
        $query = $this->createQueryBuilder('m')
            ->where('m.code = :plugin_code')
            ->setParameter('plugin_code', $pluginCode)
            ->getQuery();
        $Module = $query->getOneOrNullResult();
        if (!empty($Module)) {
            return $Module->getSubData();
        }
        return false;
    }
}
