<?php
/*
 * This file is part of the PostCarrier
 *
 * Copyright(c) 2016 IPLOGIC CO.,LTD. All Rights Reserved.
 * http://www.iplogic.co.jp
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\PostCarrier\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Id\SequenceGenerator;
use Eccube\Common\Constant;

/**
 * MailmagaCustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCarrierGroupRepository extends EntityRepository
{

    public function findAll() {
        $query = $this
            ->getEntityManager()
            ->createQuery('SELECT g, count(c) AS cnt FROM Plugin\PostCarrier\Entity\PostCarrierGroup g LEFT JOIN Plugin\PostCarrier\Entity\PostCarrierGroupCustomer c WITH g.id = c.group_id GROUP BY g ORDER BY g.id DESC');

        $result = $query->getResult(Query::HYDRATE_ARRAY);

        return $result;
    }

    /**
     * メルマガカスタマー情報を保存する
     * @param \Plugin\PostCarrier\Entity\MailmagaCustomer $MailmagaCustomer
     */
    public function save(\Plugin\PostCarrier\Entity\PostCarrierGroup $PostCarrierGroup)
    {
        $em = $this->getEntityManager();
        $em->persist($PostCarrierGroup);
        $em->flush();
    }

    public function delete(\Plugin\PostCarrier\Entity\PostCarrierGroup $PostCarrierGroup)
    {
        $em = $this->getEntityManager();
        $em->remove($PostCarrierGroup);
        $em->flush();
    }
}
